### ISSUE TITLE
Unknown error loading NuxtTurnstile in the page

### ISSUE THREAD

**Issue by XStarlink** [nuxt-modules/turnstile#311] opened 2024-05-09 13:27 UTC
### 🐛 The bug

Hello,
Thank you for your work on this module!

1. I have a problem when I load `NuxtTurnstile` in my login page, I had to use the technique described in this issue (https://github.com/nuxt-modules/turnstile/issues/250#issuecomment-1869102103) otherwise it wouldn't load at all and there was an error that crashed the page. The problem is that even with this trick, there's are errors. 

  I made a [Stackblitz reproduction](https://stackblitz.com/edit/nuxt-starter-trkpmx?file=nuxt.config.ts,pages%2Flogin.vue,pages%2Findex.vue),
  I don't know exactly why but the trick I use above isn't necessary in Stackblitz, but it is in my app.
  (I think there must be a Race condition in a real app due to the fact that there are several things loading, whereas in Stackblitz there's only the `NuxtTurnstile` component).

2. However, in Stackblitz we can also see a second problem, which is that the `NuxtTurnstile` component generates 3 invisible errors. There are three console errors created when the component is loaded, but no content or message.

_To reproduce this:_
1. Open [Stackblitz reproduction](https://stackblitz.com/edit/nuxt-starter-trkpmx?file=nuxt.config.ts,pages%2Flogin.vue,pages%2Findex.vue)
2. Open the console
3. Click on "Go to Login"
4. View console errors

<img width="497" alt="Capture d’écran 2024-05-09 à 13 33 43" src="https://github.com/nuxt-modules/turnstile/assets/34127019/24aa39be-13a8-44c1-b851-5282a96ccc23">

Thank you for your help!

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-trkpmx?file=nuxt.config.ts,pages%2Flogin.vue,pages%2Findex.vue

### 🌈 Expected behaviour

1. Consistent loading of `NuxtTurnstile` component, without tricks 
2. No error in console

**Comment by dargmuesli** [comment] 2024-05-09 22:32
I'm not sure if those invisible errors are caused by this module or by Turnstile itself. If there is some way to find that out, we can keep this issue open, otherwise it seems to me to be more or less a duplicate of #250, right?

**Comment by XStarlink** [comment] 2024-05-14 15:26
@dargmuesli  Thank you for your prompt reply, unfortunately, I really think these errors are caused by this module.
Originally, I didn't want to create a duplicate issue because the invisible errors weren't mentioned in the other one.
But it turns out that the main problem is really the module's unreliable loading.

I installed Turnstile following an attack by bots that created a lot of accounts on my site,
Since I installed this module, I've had a lot of feedback from users who have problems logging in my app or creating an account,

I've done several tests and there's definitely a big loading problem with this module, 
Sometimes it's when you come from another page, (Login -> Signup) the module creates a console error and doesn't load, so the Turnstile token isn't created and so my Signup button isn't activated.
<img width="917" alt="Capture d’écran 2024-05-14 à 15 28 26" src="https://github.com/nuxt-modules/turnstile/assets/34127019/728be962-26d1-4da5-aa9d-916963ad1031">
<img width="494" alt="Capture d’écran 2024-05-14 à 15 28 33" src="https://github.com/nuxt-modules/turnstile/assets/34127019/299f01f2-1dd0-4ae7-a0f4-3bf8cea00e3c">


Sometimes it's when you refresh the page that the module doesn't load. If I refresh the page several times, there are times when there's an error and the module doesn't load.

After reloading a page normaly:
<img width="986" alt="Capture d’écran 2024-05-14 à 15 47 35" src="https://github.com/nuxt-modules/turnstile/assets/34127019/9abeb765-2c7e-4948-949e-d027c8d91eeb">
I just reloaded the page and the module doesn't load and creates an error

I saw the PR that will add Nuxt scripts (https://github.com/nuxt-modules/turnstile/pull/306) but I didn't take the time to fully understand it, is it supposed to solve the module loading problems?

I'd like to help you find a solution to these problems so that the loading of this module is 100% reliable

**Comment by dargmuesli** [comment] 2024-05-15 06:13
Yes, I see good chances that the Nuxt scripts integration would resolve those loading issues.

**Comment by dargmuesli** [comment] 2024-06-28 02:53
The scripts integration was released just now. Would you please try out version `0.9.0` of this module by installing it, adding the `@nuxt/scripts` module to your project and seeing if this resolves the issue?

**Comment by XStarlink** [comment] 2024-06-28 11:19
@dargmuesli I've just tested it locally and it seems that the module now always loads correctly in the page even when refreshing quickly or coming from other pages!

I'm going to deploy in production and keep an eye on the error logs to see if my users still have login problems. I'll let you know if I notice any more problems.

On the other hand, I see that the module is still generating 3 phantom errors.
I've updated my reproduction with @nuxtjs/turnstile v0.9.0 and Nuxt 3.12.2 and if you refresh the page with the console open you'll see that the module still generates 3 errors that don't point to anything. (Not easy to debug...)


Thanks a lot to all the team for all the work put into the Nuxt ecosystem allowing a great DX!

**Comment by dargmuesli** [comment] 2024-06-29 22:48
Ok, thank you for the feedback! I'll close this issue for then for now. We can reopen it if the error comes up again. Regarding the phantom errors: as there is no other information on why those appear we can't do much about it now, I guess. If there is more information the same applies, we can reopen of course. Thanks again!

**Closed by dargmuesli** 2024-06-29 22:48 UTC
Labels: bug
